version: 2.1

build_jobs: &build_jobs
  jobs:
    - build-amd64
    # - build-arm
    - build-arm64
    - push-manifest:
        requires:
          - build-amd64
          # - build-arm
          - build-arm64

workflows:
  version: 2
  commit:
    <<: *build_jobs
  nightly:
    <<: *build_jobs
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

build_tasks: &build_tasks
  docker:
    - image: docker:18-git
  steps:
    - checkout

    - setup_remote_docker:
        docker_layer_caching: true

    - run:
        name: Install build dependencies.
        command: apk add --no-cache curl git jq

    - run:
        name: Add dynamic shared vars to env.
        command: .circleci/load_env.sh

    - run:
        name: Build Docker image.
        command: |
          source $BASH_ENV
          .circleci/build_image.sh

    - run:
        name: Push Docker image.
        command: |
          source $BASH_ENV
          .circleci/push_image.sh

push_manifest: &push_manifest
  docker:
    - image: docker:18-git
  steps:
    - checkout
    - setup_remote_docker

    - run:
        name: Load environment variables & pull latest release tag.
        command: |
          apk add --no-cache curl jq
          .circleci/load_env.sh

    - run:
        name: Push Docker manifest.
        command: |
          source $BASH_ENV
          .circleci/push_manifest.sh

jobs:
  build-amd64:
    <<: *build_tasks
    environment:
      TAG: amd64
      TARGET: amd64
      QEMU_ARCH: amd64
  build-arm64:
    <<: *build_tasks
    environment:
      QEMU_ARCH: aarch64
      QEMU_VERSION: v3.1.0
      TAG: arm64
      TARGET: arm64
  push-manifest: *push_manifest
